### ISSUE TITLE
Windows requires escapes "\"

### ISSUE THREAD

**Issue by FirstNormalForm** [raccrompton/BookBuilder#5]
Hello,

Thank you very much for building this.  I've built a Windows executable, but I see you've already found a source.

Here are a couple things I noticed while using this on Windows10.  When inputting engine path, I needed to use double "\\" to escape, such as:

_ENGINEPATH: "D:\\\MyDocuments\\\Games\\\Chess\\\Engines\\\stockfish\\\stockfish15\\\stockfish.exe"_

I also found the 'r' character part confusing, and messed it up once.  I had an idea of what you meant, so I was able to input my path more carefully.  But someone less coding-literate might have trouble.  Could the code handle this?

_#the filepath where the engine is stored on your computer, so it can be accessed. Keep the 'r' character_

**Comment by raccrompton** [comment]
Hmm that's very strange. I think the 'r' part is not necessary on the latest version, so hopefully that issue is solved.

But I will test with double '\' or single '\' and get back to you. Thanks so much for your help.

**Comment by FirstNormalForm** [comment]
I downloaded a new version.  I was successful with single "\\", like:

ENGINEPATH: 'D:\MyDocuments\Games\Chess\Engines\stockfish\stockfish15\stockfish.exe'

I was using double quotes instead of single quotes before; maybe that was my problem.  Thank you again for building this.

**Comment by raccrompton** [comment]
Nice, glad that worked. I’m not sure why only single quotes are accepted. Have added single quotes advice to config comments to help for now.
