### ISSUE TITLE
Request: Minimum line length

### ISSUE THREAD

**Issue by KeeghanM** [raccrompton/BookBuilder#8]
Would be nice to set a minimum line length, where even if the algorithm goes "yup that's deep enough" if it hasn't reached that depth yet, it will just pick the engines top choice for you and number one played move for your opponent.
Can also set a flag for "continue even if no games" where if there isn't any games in that position it will play engine top move for opponent and you until reaching minimum line length.

This way you get at least some kind of "example game" and thematic ideas from all lines, even if it's just 1 sample engine line.

**Comment by Esnos33** [comment]
Idea behind this program is to not set arbitrary number on moves and variation to memorise, but only that ones that are necessary. With alpha to 0.001 you should have good foundation to most lichess scenarios

**Comment by KeeghanM** [comment]
Fair enough!
